### ISSUE TITLE
Pin, block and vline features in a composite feature don't rescale properly when board is resized.

### ISSUE THREAD

**Issue by maciejkorzepa** [emepyc/tnt.board#2]
When a single feature track is used, everything works fine. However, when I create a composite feature, the positions of pin, block or vline features don't adjust when board is resized (they sit in the same place in the display). There is only some change in the display of blocks - their width seems to get updated even though their starting position doesn't. 

Line and area features seem to work well in a composite feature mode when board is resized.

**Comment by emepyc** [comment]
Fixed
