### ISSUE TITLE
Many elements (labels, fixed line) duplicated.

### ISSUE THREAD

**Issue by maciejkorzepa** [emepyc/tnt.board#6]
Many elements (labels, fixed line) are not removed in reset function and then they are duplicated in create or fixed function when the board is resized.

**Comment by emepyc** [comment]
Could you please create a small example showing the problem I can look at?

**Comment by emepyc** [comment]
As far as I can see this is now fixed. Let me know if you find any other duplications on resize:

http://bl.ocks.org/emepyc/2fdec5527dfd8458da78dcf38ff73064

**Comment by maciejkorzepa** [comment]
Yes, the duplication seems to be fixed now. However, I came across another bug in this example - when you change the size of the board and then try to pan to the right, strange things happen... (you are trapped in some strange range of the board with no features visible).

**Comment by emepyc** [comment]
Ah, that's just because I was setting the size based on the option's element, and that is interpreted as a string instead of a number.
The example is fixed now
